// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./account/backend.go

package mock_account

import (
	gomock "github.com/golang/mock/gomock"
	types "github.com/xozrc/account/types"
)

// Mock of AccountBackend interface
type MockAccountBackend struct {
	ctrl     *gomock.Controller
	recorder *_MockAccountBackendRecorder
}

// Recorder for MockAccountBackend (not exported)
type _MockAccountBackendRecorder struct {
	mock *MockAccountBackend
}

func NewMockAccountBackend(ctrl *gomock.Controller) *MockAccountBackend {
	mock := &MockAccountBackend{ctrl: ctrl}
	mock.recorder = &_MockAccountBackendRecorder{mock}
	return mock
}

func (_m *MockAccountBackend) EXPECT() *_MockAccountBackendRecorder {
	return _m.recorder
}

func (_m *MockAccountBackend) Login(at types.AccountType, secondId string, uniqueCode string) (*types.Account, error) {
	ret := _m.ctrl.Call(_m, "Login", at, secondId, uniqueCode)
	ret0, _ := ret[0].(*types.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAccountBackendRecorder) Login(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Login", arg0, arg1, arg2)
}
